### ISSUE TITLE
Array size issue

### ISSUE THREAD

**Issue by GeneralTyres** [GeneralTyres/pulpsim#2]
The “array size issue” commit in my diffusivity branch has array size problem when running. When I try to run it, it gives the error : “non-broadcastable output operand with shape (3,) doesn't match the broadcast shape (3,3)”. The K that was specified for the external mass transfer was in a shape (3, ) but the K given by the diff_constant function is (3,1). I think multiplying with the D in the function converts the K to (3,1). Is there any way we can change it back to a size (3, ) after the function?

**Comment by alchemyst** [comment]
The issue has to do with the way you calculate `transfer_rate` in line 144. You have `transfer_rate = K*A*(cl - cw[:, 0])`. K is (3,1) and cl is (3,). These arrays broadcast in numpy to form a (3,3) array in `transfer_rate` when you multiply. The solution is to have the whole thing just be (3,), so make K (3,) instead of (3,1).

**Comment by GeneralTyres** [comment]
Thanks I resized the K in the function and it worked.
